name = "MCKSP Seventh Season"
author = "NotTheTea/lndieGamer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "927d45d1916c3566310a0fca2ced1a9dc902e5ba485175fdc994f23c2b6ccd57"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
