name = "MCKSP Seventh Season"
author = "NotTheTea/lndieGamer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06fb9a3bdd160ee8a6cb107fb235597f3e1b54f2c7da90d10ee9fadb5fc2d47e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
