name = "MCKSP Seventh Season"
author = "NotTheTea/lndieGamer"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3efe5a3c17cee04b7d2dc39513df97a70854bf432a54fa9e2de3b2b6eccd4c1b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
unsup = "1.1.6"
